# -*- coding: utf-8 -*-
"""spacy_aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iB_gJcBfrdP0HufbBVNHTlhpZZibQMM8
"""

# Instala o spaCy na versão 3.2.0.
!pip install -U spacy==3.2.0

# Baixa o modelo de linguagem para português (grande).
!python -m spacy download 'pt_core_news_lg'

# Importa a biblioteca spaCy.
import spacy

# Carrega o modelo de linguagem português 'pt_core_news_lg'.
nlp = spacy.load('pt_core_news_lg')

# Exibe o tipo do objeto 'nlp' (deve ser 'spacy.lang.pt.Portuguese').
print(type(nlp))

# Exibe os nomes dos componentes do pipeline de processamento do 'nlp'.
print(nlp.pipe_names)

# Processa um texto em português com o modelo 'nlp' e armazena em 'documento'.
documento = nlp("As ações do Magazine Luiza S.A., Franca, Brasil, acumularam baixa de 70% ao ano. Assim já devolveram todos os ganhos do período da pandemeia")
#documento = nlp("Alegações extraordinárias requerem evidências extraordinárias. Carl Sagan: 'https://carlsagan.com'")

# Exibe o tamanho do vocabulário do objeto 'documento'.
len(documento.vocab)

# Exibe o tipo do objeto 'documento' (deve ser 'spacy.tokens.doc.Doc').
print(type(documento))

# Itera sobre os tokens do 'documento' e imprime o texto de cada um.
for token in documento:
  print(token.text)

# Acessa e imprime o quarto token (índice 3) do 'documento'.
print(documento[3])

# Acessa e imprime um slice de tokens do 'documento' (do índice 3 ao 4).
print(documento[3:5])

# Exibe o número total de tokens no 'documento'.
print(len(documento))

# Imprime várias propriedades de cada token no 'documento' (texto, stop word, alfanumérico, maiúsculo, pontuação, número, início de sentença).
print("Tokens: ", [token.text for token in documento])
print("Stop word: ", [token.is_stop for token in documento])
print("Alfanumérico: ", [token.is_alpha for token in documento])
print("Maísculo: ", [token.is_upper for token in documento])
print("Pontuação: ", [token.is_punct for token in documento])
print("Número: ", [token.like_num for token in documento])
print("Sentença Inicial: ", [token.is_sent_start for token in documento])

# Imprime o texto e o formato léxico (shape_) de cada token no 'documento'.
print("Tokens: ", [token.text for token in documento])
print("Formato: ", [token.shape_ for token in documento])

# Itera sobre os tokens e identifica se são números ou pontuações.
for token in documento:
  if token.like_num:
    print("Número encontrado: ", token.text)
  if token.is_punct:
    print("Pontuação encontrada; ", token.text)

# Itera sobre os tokens e imprime seu texto, parte da fala (pos_), dependência sintática (dep_), lema (lemma_) e formato (shape_).
for token in documento:
  print(token.text, " - ", token.pos_ , " - ", token.dep_ , " - ", token.lemma_ , " - ", token.shape_)

# Itera sobre os tokens e imprime seu texto e características morfológicas (morph).
for token in documento:
  print(token.text, " - ", token.morph)

# Itera sobre os tokens e imprime seu texto e a tag gramatical (tag_).
for token in documento:
  print(token.text, " - ", token.tag_)

# Itera sobre as entidades nomeadas (NER) no 'documento' e imprime o texto e o rótulo de cada entidade.
for ent in documento.ents:
  print(ent.text, " - ", ent.label_)

# Itera sobre os tokens do 'documento' e imprime as stop words.
for token in documento:
  if token.is_stop:
    print("Stop word: ", token.text)

# Itera e imprime todas as palavras-chave (stop words) padrão do modelo 'nlp'.
for words in nlp.Defaults.stop_words:
  print(words)

# Adiciona a palavra "eita" à lista de stop words do modelo 'nlp' e a marca como stop word no vocabulário.
nlp.Defaults.stop_words.add("eita")
nlp.vocab['eita'].is_stop = True

# Verifica se a palavra "eita" está marcada como stop word no vocabulário.
nlp.vocab['eita'].is_stop

# Processa um texto, remove stop words e imprime o texto original e a lista de palavras sem stop words.
token_lista = []
for token in documento:
  token_lista.append(token.text)

stop_lista = []
for words in nlp.Defaults.stop_words:
  stop_lista.append(words)

semstop = [word for word in token_lista if not word in stop_lista]

print(documento.text)
print(semstop)

# Imprime o hash numérico (ID) da string "dados" no vocabulário e a string associada a um hash.
print("Hash: ", nlp.vocab.strings["dados"])
print("Hash: ", documento.vocab.strings["dados"])
print("String: ", nlp.vocab.strings[6013848609874238634])

# Acessa o léxico para a palavra "dados" e imprime suas propriedades (texto, hash, is_alpha, is_lower).
lex = nlp.vocab["dados"]
print(lex.text, " - ", lex.orth, " - ", lex.is_alpha, " - ", lex.is_lower)

# Imprime o vetor de embeddings de um documento (frase).
#print(nlp("dados").vector.shape)
#print(nlp("dados").vector)
print(nlp("dados são uma nova forma de ver o mundo").vector)

# Calcula e imprime a similaridade entre dois documentos (frases).
documento1 = nlp("Ele viaja regularmente de carro")
documento2 = nlp("Ela regularmente de avião viaja")
print(documento1.similarity(documento2))
print(documento2.similarity(documento1))

# Calcula e imprime a similaridade entre dois tokens específicos de um documento.
documento3 = nlp("Devemos dizer comprimento ou cumprimento?")
tokenA = documento3[2]
print(tokenA)
tokenB = documento3[4]
print(tokenB)
print(tokenA.similarity(tokenB))

# Calcula e imprime a similaridade entre dois spans (segmentos de texto) de um documento.
documento4 = nlp("Ele pede descrição. Ele pede discrição")
partA = documento4[0:3]
print(partA)
partB = documento4[4:7]
print(partB)
print(partA.similarity(partB))

# Demonstra o uso do Matcher para encontrar padrões de telefone em um texto.
from typing import Match
from spacy.matcher import Matcher

documento5 = nlp("Você pode ligar para (51) - 9964656570 ou (11) 12344988 ")

matcher = Matcher(nlp.vocab)
padrao = [{"ORTH": "("} ,{"SHAPE": "dd"},{"ORTH": ")"}, {"ORTH": "-", "OP":"?"} , {"IS_DIGIT": True}]
matcher.add("telefone", [padrao])
matches = matcher(documento5)
for id, inicio, fim in matches:
  print(documento5[inicio:fim])

# Demonstra o uso do Matcher para encontrar diferentes variações da palavra "microrganismos" em um texto.
documento6 = nlp("Estamos infectados com micro organismos. MICROORGANISMOS são perigosos. Não enxergamos micro-organismos")
matcher = Matcher(nlp.vocab)
padrao1 = [{"LOWER":"micro-organismos"}]
padrao2 = [{"LOWER":"microorganismos"}]
padrao3 = [{"LOWER":"micro"}, {"LOWER":"organismos"}]

matcher.add("padrao", [padrao1,padrao2,padrao3])

matches = matcher(documento6)
for id, inicio, fim in matches:
  print(documento6[inicio:fim])

# Renderiza as entidades nomeadas (NER) do 'documento' graficamente no Jupyter.
from spacy import displacy
displacy.render(documento,style="ent", jupyter=True)

# Define um título para o documento e renderiza as dependências sintáticas do 'documento' graficamente com estilo personalizado.
documento.user_data['title'] = "Exemplo"
displacy.render(documento,style="dep", jupyter=True,
                options={'compact': True, 'distance' : 80, 'color': '#FFFFFF', 'bg': '#000000', 'font': 'Arial' })

# Imprime os nomes dos componentes do pipeline de processamento do 'nlp' (pipeline normal).
print("Pipeline Normal: ", nlp.pipe_names)

# Remove o componente 'tok2vec' do pipeline e imprime o pipeline atualizado.
nlp.remove_pipe('tok2vec')
print("Pipeline sem tok2vec: ", nlp.pipe_names)

# Adiciona o componente 'tok2vec' de volta ao pipeline após 'morphologizer' e imprime o pipeline normalizado.
nlp.add_pipe('tok2vec', after='morphologizer')
print("Pipeline Normal: ", nlp.pipe_names)