# -*- coding: utf-8 -*-
"""spacy_pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JeJYPhI_D1ivp9pxpf9AECNoTvmCag1

# Spacy Versão 2.0: Timeline Comparativa (SM, MD, LG)
Este notebook apresenta uma v2 da pratica da aula do card1 na qual há comparação detalhada entre os modelos de Português da Spacy usando um contexto de 500 palavras.
"""

# 1. SETUP E CONTEXTO
!python -m spacy download pt_core_news_sm
!python -m spacy download pt_core_news_md
!python -m spacy download pt_core_news_lg

import spacy
from spacy import displacy

modelos = {
    'Pequeno (sm)': spacy.load('pt_core_news_sm'),
    'Médio (md)': spacy.load('pt_core_news_md'),
    'Grande (lg)': spacy.load('pt_core_news_lg')
}

texto_contexto = """
A inteligência artificial (IA) deixou de ser uma promessa futurista para se tornar a espinha dorsal da inovação tecnológica global no século XXI. Empresas como OpenAI, Google, Microsoft e NVIDIA estão na vanguarda desta revolução, investindo bilhões de dólares no desenvolvimento de modelos de linguagem de larga escala (LLMs). Em São Paulo, o ecossistema de startups de tecnologia tem absorvido essas ferramentas para otimizar processos que vão desde a logística portuária em Santos até a análise financeira na Faria Lima. A revolução começou de forma silenciosa, mas o lançamento do ChatGPT pela OpenAI em San Francisco mudou a percepção pública quase instantaneamente.

O impacto da IA não se limita apenas ao código de software. No setor de saúde, algoritmos de deep learning estão auxiliando médicos em hospitais renomados, como o Albert Einstein e o Sírio-Libanês, a identificar patologias em exames de imagem com uma precisão superior à visão humana em certos casos. Contudo, essa evolução traz desafios éticos significativos. A questão da privacidade dos dados e o viés algorítmico são temas centrais em debates no Congresso Nacional em Brasília, onde legisladores tentam criar um marco regulatório que proteja o cidadão sem sufocar a competitividade das empresas brasileiras.

A infraestrutura necessária para sustentar esses modelos é colossal. A NVIDIA, sediada em Santa Clara, viu seu valor de mercado disparar devido à demanda sem precedentes por GPUs, que são os motores de processamento por trás do treinamento de redes neurais. Enquanto isso, o Google DeepMind continua explorando as fronteiras da Inteligência Artificial Geral (AGI), buscando sistemas que possam aprender qualquer tarefa intelectual que um ser humano possa realizar. Na Europa, a União Europeia lidera o mundo com o 'AI Act', a primeira legislação abrangente para mitigar riscos de segurança e direitos fundamentais.

No Brasil, o cenário é de otimismo cauteloso. A educação técnica precisa evoluir rapidamente para que os profissionais brasileiros não sejam apenas consumidores, mas criadores de tecnologia. O uso de IA na agricultura de precisão no Mato Grosso já mostra como a análise de dados via satélite pode aumentar a produtividade das safras de soja e milho, reduzindo o desperdício de recursos hídricos. Portanto, a jornada da inteligência artificial está apenas começando, e a colaboração entre governos, academia e setor privado será o fator determinante para garantir que os benefícios dessa tecnologia sejam distribuídos de forma equitativa por toda a sociedade, promovendo um crescimento econômico sustentável e inclusivo.
"""
print("Modelos carregados e contexto definido.")

"""## Timeline 1: Capacidade do Pipeline
Analisamos quais componentes cada modelo utiliza para processar o texto.
"""

import spacy

if 'Grande (lg)' in modelos:
    modelos['Grande (lg)'] = spacy.load('pt_core_news_lg')

for nome, nlp in modelos.items():
    try:
        doc = nlp(texto_contexto)
        print(f"--- {nome} ---\nPipeline: {nlp.pipe_names}\nTokens: {len(doc)}\n")
    except Exception as e:
        print(f"Erro ao processar com {nome}: {e}")

"""## Timeline 1.2: Manipulação de Pipeline e Vocabulário
Demonstrando como alterar o fluxo de processamento e acessar o armazenamento interno de strings (Hashes).
"""

# Testando Hashes no Vocabulário
nlp_lg = modelos['Grande (lg)']
hash_ia = nlp_lg.vocab.strings["inteligência"]
print(f"Hash de 'inteligência': {hash_ia}")
print(f"String do Hash {hash_ia}: {nlp_lg.vocab.strings[hash_ia]}")

# Modificando o Pipeline em tempo de execução
print(f"\nPipeline Original (lg): {nlp_lg.pipe_names}")
nlp_lg.remove_pipe('tok2vec')
print(f"Pipeline após remoção: {nlp_lg.pipe_names}")
nlp_lg.add_pipe('tok2vec', before='morphologizer')
print(f"Pipeline restaurado: {nlp_lg.pipe_names}")

"""## Timeline 1.1: Análise Morfológica (POS Tagging)
Aprofundando na gramática: como cada modelo entende a função das palavras no novo contexto.
"""

import pandas as pd
import spacy

modelos['Grande (lg)'] = spacy.load('pt_core_news_lg')

exemplo_frase = "Algoritmos de deep learning estão auxiliando médicos."
resultados_pos = []

for nome, nlp in modelos.items():
    try:
        doc = nlp(exemplo_frase)
        for token in doc:
            resultados_pos.append({
                "Modelo": nome,
                "Texto": token.text,
                "POS": token.pos_,
                "Lemma": token.lemma_,
                "Morfologia": str(token.morph)
            })
    except Exception as e:
        print(f"Erro no modelo {nome}: {e}")

df_pos = pd.DataFrame(resultados_pos)
display(df_pos.head(24))

"""## Timeline 2: Inteligência em Extração (NER)
Como a precisão varia entre os tamanhos dos modelos ao identificar nomes e locais.
"""

for nome, nlp in modelos.items():
    doc = nlp(texto_contexto)
    print(f"\n>>> Modelo {nome} ({len(doc.ents)} entidades):")
    for ent in list(doc.ents)[:8]:
        print(f"  {ent.text} -> {ent.label_}")

"""## Timeline 3: Vetores e Similaridade
Demonstração de como os modelos maiores usam Word Embeddings reais vs o modelo pequeno.
"""

t1, t2 = "IA", "Tecnologia"
for nome, nlp in modelos.items():
    score = nlp(t1).similarity(nlp(t2))
    status = "(Vetores de Palavras)" if "sm" not in nome.lower() else "(Tensores de Contexto)"
    print(f"{nome}: {score:.4f} {status}")

"""## Timeline 3.1: Matriz de Similaridade Avançada
Em vez de apenas dois termos, vamos testar uma matriz de conceitos tecnológicos para ver a consistência dos vetores do modelo `lg` vs `sm`.
"""

conceitos = ["Inovação", "Dinheiro", "Saúde", "Algoritmo", "Brasil"]
matriz_sim = []

for nome, nlp in modelos.items():
    # Comparamos 'Inovação' com todos os outros conceitos
    base = nlp("Inovação")
    for conceito in conceitos:
        sim = base.similarity(nlp(conceito))
        matriz_sim.append({"Modelo": nome, "Termo": conceito, "Similaridade com 'Inovação'": round(sim, 4)})

df_sim = pd.DataFrame(matriz_sim).pivot(index='Termo', columns='Modelo', values="Similaridade com 'Inovação'")
display(df_sim)

"""## Timeline 3.3: Similaridade de Spans e Lexical Attributes
Comparando segmentos de texto (spans) e verificando propriedades léxicas (como `shape_` e `like_num`).
"""

# Comparando similaridade entre frases específicas do contexto
doc_comp = modelos['Grande (lg)'](texto_contexto)

span1 = doc_comp[0:5]   # "A inteligência artificial (IA)"
span2 = doc_comp[20:25] # "inovação tecnológica global no"

print(f"Span 1: {span1.text}")
print(f"Span 2: {span2.text}")
print(f"Similaridade entre Spans: {span1.similarity(span2):.4f}")

# Atributos Léxicos
print(f"\nAtributos do Token '{doc_comp[0]}':")
print(f"Shape: {doc_comp[0].shape_} | Alpha: {doc_comp[0].is_alpha} | Stop: {doc_comp[0].is_stop}")

"""## Timeline 3.2: Stop Words e Customização do Vocabulário
Demonstrando como expandir o conhecimento do modelo para o domínio específico de tecnologia.
"""

# Adicionando stop words customizadas baseadas no contexto
for nome, nlp in modelos.items():
    nlp.Defaults.stop_words.add("bilhões")
    nlp.vocab["bilhões"].is_stop = True

# Testando a filtragem no modelo Grande
doc_lg = modelos['Grande (lg)'](texto_contexto)
palavras_filtradas = [t.text for t in doc_lg if not t.is_stop and not t.is_punct]

print(f"Total de palavras originais: {len(doc_lg)}")
print(f"Total após limpeza de Stop Words: {len(palavras_filtradas)}")
print(f"Exemplo de palavras limpas: {palavras_filtradas[:15]}")

"""## Timeline 3.4: Padronização com Matcher
Usando o `Matcher` para encontrar padrões específicos (como siglas entre parênteses ou termos compostos) no texto longo.
"""

from spacy.matcher import Matcher

nlp_lg = modelos['Grande (lg)']
matcher = Matcher(nlp_lg.vocab)

padrao_ia = [{"LOWER": "inteligência"}, {"LOWER": "artificial"}]
padrao_sigla = [{"ORTH": "("}, {"IS_UPPER": True}, {"ORTH": ")"}]

matcher.add("IA_TERM", [padrao_ia])
matcher.add("SIGLA", [padrao_sigla])

doc_matcher = nlp_lg(texto_contexto)
matches = matcher(doc_matcher)

print("Ocorrências encontradas pelo Matcher:")
for match_id, start, end in matches:
    string_id = nlp_lg.vocab.strings[match_id]
    span = doc_matcher[start:end]
    print(f"[{string_id}] -> {span.text}")

"""## Timeline 4: Análise Visual de Dependências
Renderização sintática usando o modelo 'lg' para máxima precisão.
"""

doc_viz = modelos['Grande (lg)']("A OpenAI investe bilhões em tecnologia.")
displacy.render(doc_viz, style='dep', jupyter=True, options={'distance': 110})

"""## Timeline 4.1: Visualização de Entidades (Estilo 'Ent')
Renderizando o texto completo destacando as entidades identificadas pelo modelo Grande.
"""

# Renderizando as entidades do texto de 500 palavras
doc_ent = modelos['Grande (lg)'](texto_contexto)
displacy.render(doc_ent, style="ent", jupyter=True)