# -*- coding: utf-8 -*-
"""gerador_aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HSKXBq5XgMWGYKycN2fJXAOz3IszqfW
"""

# Instala a biblioteca transformers
!pip install transformers

# Importa as bibliotecas transformers e pipeline
import transformers
from transformers import pipeline

# Inicializa o gerador de texto com um modelo GPT-2 em português
gerador = pipeline("text-generation", model="pierreguillou/gpt2-small-portuguese")

# Define um texto de entrada e gera texto continuado, imprimindo o resultado
texto = "Em sentido estrito, ciência refere-se ao sistema de adquirir conhecimento baseado no método científico."
resultado = gerador(texto, max_length=60, do_sample=True)
print(resultado)

