# -*- coding: utf-8 -*-
"""gerador_prática.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCNdPUfJ_khQZ3aZrknb-SVRDHH94AbG
"""

# Instala a biblioteca transformers
!pip install transformers

# Importa as bibliotecas transformers e pipeline
import transformers
from transformers import pipeline

# Inicializa o gerador de texto com um modelo GPT-2 em português
gerador = pipeline("text-generation", model="pierreguillou/gpt2-small-portuguese")

# Define um texto de entrada e gera texto continuado, imprimindo o resultado
texto = "Funções de soma, subtração, divisão e multiplicação implementadas em python por funcoes"
resultado = gerador(texto, max_length=60, do_sample=True)
print(resultado)

