# -*- coding: utf-8 -*-
"""perguntaserespostas_pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbsFJGxX45E-GeIgs5pB_rz2eNa4SE4J
"""

# Instala a biblioteca transformers para processamento de linguagem natural
!pip install "transformers<5.0"

# Importa a biblioteca transformers e a função pipeline para carregar modelos pré-treinados
import transformers
from transformers import pipeline

# Inicializa o pipeline de question-answering com o termo aceito pela sua versão atual
qea = pipeline("question-answering", model="pierreguillou/bert-base-cased-squad-v1.1-portuguese")

# Contexto simplificado focado apenas no Brasil para evitar alucinações
texto = "O Brasil é a única seleção pentacampeã mundial. Suas conquistas de Copa do Mundo ocorreram em 1958, 1962, 1970, 1994 e 2002."

# Pergunta direta sobre os anos de título
pergunta = "Quais foram os cinco anos em que o Brasil foi campeão do mundo?"

resposta = qea(question=pergunta, context=texto)

print("Pergunta: ", pergunta)
print("Resposta: ", resposta['answer'])
print("Score: ", resposta['score'])