# -*- coding: utf-8 -*-
"""perguntaserespostas_aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EkM3aJEFwntTOxXa3lzUkAu5HEjwg6c
"""

# Instala a biblioteca transformers para processamento de linguagem natural
!pip install "transformers<5.0"

# Importa a biblioteca transformers e a função pipeline para carregar modelos pré-treinados
import transformers
from transformers import pipeline

# Inicializa o pipeline de question-answering com o termo aceito pela sua versão atual
qea = pipeline("question-answering", model="pierreguillou/bert-base-cased-squad-v1.1-portuguese")

#Define o texto de contexto e a pergunta, executa o modelo e exibe o resultado
texto = "Carl Sagan foi um cientista norte-americano. Sagan é autor de mais de 600 publicações científicas e também de mais de vinte livros de ciência e ficção científica."
#pergunta = "Quantos livros Carl Sagan tem publicado?"
#pergunta = "Quem é Carl Sagan?"
pergunta = "Quantas publicações cientificas Carl Sagan tem publicado?"

resposta = qea(question=pergunta, context=texto)

print("Pergunta: ", pergunta)
print("Resposta: ", resposta['answer'])
print("Score: ", resposta['score'])