# -*- coding: utf-8 -*-
"""preencherlacunas_pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lj9hcRMVThUPKGjGFaw-k00xA4XpdH4B
"""

# Instala a biblioteca transformers da Hugging Face
!pip install transformers

# Importa a biblioteca transformers e a função pipeline para carregar modelos pré-treinados
import transformers
from transformers import pipeline

# Inicializa o pipeline de 'fill-mask' usando o modelo BERT especializado em português (BERTimbau)
mascarar = pipeline("fill-mask", model="neuralmind/bert-base-portuguese-cased")

# Define uma string contendo código Python com uma lacuna ([MASK])
codigo_python = "def somar(a, b): return a [MASK] b"

# Usa o modelo para prever as palavras (ou símbolos) mais prováveis para preencher a máscara
sugestoes_codigo = mascarar(codigo_python)

# Exibe o código original e as sugestões encontradas pelo modelo
print(f"\033[1mCódigo Pyhton Base:\033[0m {codigo_python}\n")
print("Sugestões do modelo para completar o operador:")

for i, predicao in enumerate(sugestoes_codigo):
    print(f"{i+1}. {predicao['sequence']}")
    print(f"   (Token: '{predicao['token_str']}' | Confiança: {predicao['score']:.4%})")
    print("-" * 40)

# Define exemplos de código em diferentes linguagens (Go e Python) com máscaras
codigo_go = "func somar(a int, b int) int { return a [MASK] b }"
codigo_python = "def somar(a, b): return a [MASK] b"

# Processa ambos os textos através do pipeline de máscara
resultados_go = mascarar(codigo_go)
sugestoes_codigo = mascarar(codigo_python)

# Exibe os resultados para o código em Go
print(f"\033[1mCódigo Go Base:\033[0m {codigo_go}\n")
for x in range(len(resultados_go)):
    predicao = resultados_go[x]
    print(f"Sugestão {x+1}: {predicao['sequence']}")
    print(f"Token: '{predicao['token_str']}' | Score: {predicao['score']:.4f}")
    print("-" * 30)

# Exibe os resultados para o código em Python
print(f"\033[1mCódigo Pyhton Base:\033[0m {codigo_python}\n")
for i, predicao in enumerate(sugestoes_codigo):
    print(f"{i+1}. {predicao['sequence']}")
    print(f"   (Token: '{predicao['token_str']}' | Confiança: {predicao['score']:.4%})")
    print("-" * 40)