# -*- coding: utf-8 -*-
"""preencherlacunas_aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgtuFPFLL_C0MfDVoKwl8MKjkr-XWj5W
"""

!pip install transformers

import transformers
from transformers import pipeline

mascarar = pipeline("fill-mask", model="neuralmind/bert-base-portuguese-cased")

texto = mascarar("Existe uma chance do copo cair no [MASK]")
for x in range(len(texto)):
  print(texto[x])

texto = mascarar(["Existe uma chance do copo cair no [MASK]","Brasília é a capital do [MASK]"])
for x in range(len(texto)):
  print(texto[x])

