# -*- coding: utf-8 -*-
"""resumo_prática.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l87WfmpNqNHF4Bfdzj5bP0DxZmcZGQNa
"""

# Instala as bibliotecas transformers, torch
!pip install transformers==4.44.2 torch

# Importa as bibliotecas necessárias do transformers
import transformers
from transformers import pipeline

# Inicializa o pipeline de sumarização
resumidor = pipeline("summarization")

# Define o texto a ser sumarizado
texto = """Inteligência artificial (frequentemente abreviada por IA ou AI, do inglês Artificial Intelligence) é, de forma genérica, a capacidade de máquinas demonstrarem inteligência, raciocínio e aprendizado de forma semelhante ao pensamento humano.[1][2] O campo busca desenvolver máquinas autónomas ou sistemas especialistas capazes de simular o comportamento humano e realizar tarefas complexas de forma independente.[3] Trata-se de um sistema que permite aos computadores executar funções avançadas, como a análise de dados em grande escala e a formulação de previsões ou recomendações.[1][4] Como campo de pesquisa na ciência da computação, dedica-se ao estudo e desenvolvimento de métodos e softwares que capacitam as máquinas a perceberem o seu ambiente e a utilizarem o aprendizado para tomar ações que maximizem as hipóteses de atingir objetivos definidos.[5]

A história da IA remonta à década de 1950, fundamentada em conceitos que remontam ao filósofo grego Aristóteles. Em 1950, o matemático inglês Alan Turing teorizou sobre a possibilidade de uma máquina pensar e imitar o comportamento humano inteligente, esboçando uma proposta de pesquisa pioneira para tornar este objetivo viável,[6] uma visão partilhada por pesquisadores contemporâneos como Herbert Simon. Fundada oficialmente como disciplina académica em 1956,[7] a inteligência artificial passou por múltiplos ciclos de otimismo ao longo de sua história,[8] intercalados por períodos de estagnação e perda de financiamento ("invernos da IA"). O interesse e os recursos aumentaram substancialmente a partir de 2012, quando a aprendizagem profunda superou os modelos tecnológicos anteriores. Este crescimento acelerou após 2017[9] e, no início da década de 2020, o setor recebeu investimentos de milhares de milhões de dólares, consolidando um rápido progresso conhecido como o boom da IA. Contudo, o surgimento da IA generativa avançada trouxe consigo debates sobre consequências não intencionais no presente e preocupações quanto aos riscos da IA no futuro, impulsionando discussões globais acerca de políticas regulatórias voltadas para a segurança e os benefícios da tecnologia.

As aplicações de IA modernas incluem mecanismos avançados de busca na web (como o Google Search); sistemas de recomendação (utilizados por plataformas como YouTube, Amazon e Netflix); assistentes virtuais (como Google Assistant, Siri e Alexa); veículos autónomos (como os da Waymo); ferramentas generativas e criativas (como ChatGPT, DeepSeek e AI art); além de análises e desempenhos sobre-humanos em jogos de estratégia como xadrez e Go. No entanto, muitas destas tecnologias deixam de ser percebidas como IA à medida que se tornam comuns no quotidiano.[10][11] Exemplos disto incluem o reconhecimento ótico de caracteres (OCR) para extração de texto em imagens,[1] a transformação de conteúdos não estruturados em dados legíveis e os sistemas automáticos de tradução de texto e de voz.[4]

Por ser uma área multidisciplinar, a IA abrange campos como a ciência da computação, estatística, engenharia de hardware e de software, linguística, neurociência e filosofia.[1] Os seus subcampos focam-se em objetivos e ferramentas específicas. As metas tradicionais da investigação em IA englobam o raciocínio, a representação de conhecimento, o planeamento, a aprendizagem, o processamento de linguagem natural, a perceção e o suporte à robótica. A longo prazo, destaca-se o desenvolvimento da inteligência geral — a capacidade de uma máquina realizar qualquer tarefa humana com um nível de eficiência pelo menos equivalente.[12] Para alcançar tais propósitos, os investigadores integram técnicas de otimização matemática, lógica formal, redes neurais artificiais e métodos baseados em estatística, pesquisa operacional, economia e psicologia.[13]"""

# Realiza a sumarização do texto e imprime o resultado
resumo = resumidor(texto, max_length=100, min_length=50, truncation=True)
print(resumo)