# -*- coding: utf-8 -*-
"""nltk_pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipPowPVeNqlNonISTUYK2Ged5jHI4FBs

### Processamento de Linguagem Natural 2.0
Nesta versão, aplicamos os conceitos de NLTK em um texto sobre Tecnologia e Inteligência Artificial.
"""

import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import SnowballStemmer
from nltk.tag import pos_tag

# Download dos recursos necessários corrigidos
nltk.download("stopwords")
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

# Novo texto de contexto: Tecnologia e IA
novo_texto = "A inteligência artificial está transformando o mundo moderno. Máquinas aprendem com dados e resolvem problemas complexos. Será que o futuro pertence aos algoritmos? O conhecimento humano é a base de tudo."
print(f"Texto Original:\n{novo_texto}")

# 1. Tokenização de Sentenças e Palavras
sentencas = sent_tokenize(novo_texto, language="portuguese")
tokens = word_tokenize(novo_texto, language="portuguese")

print(f"Total de sentenças: {len(sentencas)}")
print(f"Primeiros 10 tokens: {tokens[:10]}")

# 2. Limpeza de Dados (Stopwords e Pontuação)
lingua = "portuguese"
stops = set(stopwords.words(lingua))

# Filtra palavras irrelevantes e pontuação simultaneamente
palavras_limpas = [
    p.lower() for p in tokens
    if p.lower() not in stops and p not in string.punctuation
]

print(f"Tokens originais: {len(tokens)}")
print(f"Tokens após limpeza: {len(palavras_limpas)}")
print(f"Palavras filtradas: {palavras_limpas}")

# 3. Distribuição de Frequência
frequencia = nltk.FreqDist(palavras_limpas)
print("Top 3 palavras mais frequentes:")
display(frequencia.most_common(3))

# 4. Stemming (Redução ao Radical) - Usando Snowball para Português
stemmer_pt = SnowballStemmer("portuguese")
radicais = [stemmer_pt.stem(p) for p in palavras_limpas]

print("Comparação: Palavra -> Radical")
for original, radical in zip(palavras_limpas[:5], radicais[:5]):
    print(f"{original} -> {radical}")

# 5. Part-of-Speech Tagging (POS)
# Nota: O tagger padrão do NLTK é otimizado para Inglês.
etiquetas = pos_tag(palavras_limpas)
print("Classificação Gramatical (Simplificada):")
print(etiquetas[:10])