# -*- coding: utf-8 -*-
"""nltk_aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpSTfTc2XO6UuLoRO69oCVs7uaPOiJ1A
"""

# Importa as bibliotecas NLTK necessárias e baixa os dados exigidos para o processamento de texto.
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer, SnowballStemmer, LancasterStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.tag import pos_tag, pos_tag_sents
import string
nltk.download("stopwords")
nltk.download('punkt_tab')
nltk.download('tagsets_json')
nltk.download("wordnet")
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker_tab')
nltk.download("words")

# Define o texto de entrada e o imprime no console.
Texto = "Nós somos feitos de poeira de estrelas. Nós somos uma maneira de o cosmos se autoconhecer. A imaginação nos leva a mundos que nunca sequer existiram. Mas sem ela não vamos a lugar algum.  " # Define the input text
print(Texto)

# Abre a interface gráfica do usuário do NLTK Downloader (isso pode bloquear a execução em alguns ambientes).
nltk.download()

# Tokeniza o texto de entrada em frases usando as regras da língua portuguesa.
sentencas = sent_tokenize(Texto, language="portuguese")
print(type(sentencas))
print(sentencas)

# Imprime o número total de frases identificadas no texto.
print(len(sentencas))

# Tokeniza o texto de entrada em palavras individuais usando as regras da língua portuguesa.
tokens = word_tokenize(Texto, language="portuguese")
print(tokens)
print(len(tokens))

# Recupera e exibe a lista de stopwords em português.
stops = stopwords.words("portuguese")
print(len(stops))
print(stops)

# Remove as stopwords da lista tokenizada de palavras.
palavras_sem_stopwords = [p for p in tokens if p not in stops]
print(len(palavras_sem_stopwords))
print(Texto)
print(palavras_sem_stopwords)

# Imprime todos os caracteres de pontuação padrão disponíveis no módulo string.
print(string.punctuation)

# Remove a pontuação da lista de palavras que já estão sem stopwords.
palavras_sem_pontuacao = [p for p in palavras_sem_stopwords if p not in string.punctuation]
print(len(palavras_sem_pontuacao))
print(Texto)
print(palavras_sem_pontuacao)

# Calcula e exibe a distribuição de frequência das palavras sem pontuação.
frequencia = nltk.FreqDist(palavras_sem_pontuacao)
frequencia

# Identifica e exibe as 5 palavras mais comuns da distribuição de frequência.
mais_comuns = frequencia.most_common(5)
mais_comuns

# Aplica a lematização Porter nas palavras (principalmente para o inglês, então os resultados para o português podem ser imprecisos).
stemmer = PorterStemmer()
stem1  = [stemmer.stem(word) for word in palavras_sem_stopwords]
print(palavras_sem_pontuacao)
print(stem1)

# Aplica a lematização Snowball especificamente para a língua portuguesa.
stemmer2 = SnowballStemmer("portuguese")
stem2 = [stemmer2.stem(word) for word in palavras_sem_pontuacao]
print(palavras_sem_pontuacao)
print(stem2)

# Aplica a lematização Lancaster nas palavras (principalmente para o inglês, então os resultados para o português podem ser imprecisos).
stemmer3 = LancasterStemmer()
stem3 = [stemmer3.stem(word) for word in palavras_sem_pontuacao]
print(palavras_sem_pontuacao)
print(stem3)

# Exibe informações de ajuda para o conjunto de tags Part-of-Speech do Penn Treebank.
nltk.help.upenn_tagset()

# Realiza a marcação Part-of-Speech (POS) nas palavras em português. Note que o tagger padrão do NLTK é treinado em inglês.
pos = nltk.pos_tag(palavras_sem_pontuacao)
print(pos)

# Tokeniza o texto em frases e depois cada frase em palavras, seguido pela marcação POS para cada frase.
token2 = sent_tokenize(Texto)

ntokens = []
for tokensentenca in token2:
  ntokens.append(word_tokenize(tokensentenca))

print(ntokens)

possenteca = pos_tag_sents(ntokens)
print(possenteca)

# Aplica a lematização WordNet às palavras. Este lematizador é principalmente para inglês e terá efeito limitado em palavras portuguesas.
lemmatizer = WordNetLemmatizer()
resultado = [lemmatizer.lemmatize(palavra) for palavra in palavras_sem_stopwords]
print(palavras_sem_pontuacao)
print(resultado)

# Demonstra o Reconhecimento de Entidades Nomeadas (NER) usando um exemplo de texto em inglês.
texto_en = "Barack Obama foi um presidente dos EUA"
token3 = word_tokenize(texto_en)
tags = pos_tag(token3)
en = nltk.ne_chunk(tags)
print(en)